apiVersion: apps/v1
kind: Deployment
metadata:
  name: marvin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marvin
  template:
    metadata:
      labels:
        app: marvin
    spec:
      containers:
      - name: marvin
        image: zzstoatzz/ayy:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"

        env:
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: gh-util-token
              key: GITHUB_TOKEN

        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-api-key
              key: OPENAI_API_KEY
        
        - name: PREFECT_API_URL
          valueFrom:
            secretKeyRef:
              name: prefect-api-url
              key: PREFECT_API_URL

        - name: PREFECT_API_KEY
          valueFrom:
            secretKeyRef:
              name: prefect-api-key
              key: PREFECT_API_KEY